# NumPy

- [NumPy GitHub](https://github.com/numpy/numpy)
- [NumPy website](https://numpy.org/)

NumPy e uma biblioteca fundamental para computacao cientifica com Python. 


Foi desenvolvida para liguagem de programacao Python, permite a realizao de operacoes matriciais, suportando grande e matrizes multi-dimensionais, alem de possuir grande colecao de funcoes matematicas de alto nivel oprando com matrizes.

E uma das bibliotecas de raiz existente na distribuicao de Anaconda (distribuicao de Python).

### Importacao de NumPy

In [7]:
import numpy as np

##### Lista de dados

In [1]:
for num in range(1, 15):
    print(num)

1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [3]:
# minha lista: m_lista
m_lista = [num for num in range(1, 16)]
m_lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [5]:
# outra_lista 
o_lista = [[1,2,3], [4,5,6], [7,8,9]]
o_lista

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
o_lista[1][2]

6

#### Matrizes

In [9]:
# matriz
np.array(o_lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# vector
np.arange(1, 15)

In [10]:
vec = np.arange(1, 15)
vec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
vec[13]

14

In [12]:
vec.shape

(14,)

In [13]:
# np.linspace(inicio, fim, quantia_divisao)
np.linspace(1, 50, 9)

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

#### seccionar

In [14]:
matriz = np.arange(1, 50)
matriz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
# do inicio ate 20
parte_matriz = matriz[:20]
parte_matriz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
# de 20 ate 30
matriz[20:30], matriz[20:]

(array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]))

In [17]:
# os ultimos 5
matriz[-7:]

array([43, 44, 45, 46, 47, 48, 49])

##### substituir

In [18]:
parte_matriz[:] = 5500

In [19]:
matriz

array([5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500,
       5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49])

In [20]:
matriz.reshape((7,7))

array([[5500, 5500, 5500, 5500, 5500, 5500, 5500],
       [5500, 5500, 5500, 5500, 5500, 5500, 5500],
       [5500, 5500, 5500, 5500, 5500, 5500,   21],
       [  22,   23,   24,   25,   26,   27,   28],
       [  29,   30,   31,   32,   33,   34,   35],
       [  36,   37,   38,   39,   40,   41,   42],
       [  43,   44,   45,   46,   47,   48,   49]])

In [21]:
matriz > 40

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

## Aleatorio (random)
#### Semente (seed) para guarantir a repeticao nas mesma condicao

In [22]:
np.random.seed(2020)
np.random.rand(4)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571])

__Inteiro__

In [ ]:
# numeros inteiros aleatorios
np.random.randint( 1000)

In [ ]:
# lista de numero  aleaotrio  inteiro
np.random.randint(1, 45, 5)

In [ ]:
np.random.randint(0,10, 2)

__Decimal__

In [ ]:
# numero aleatorio no intervalo [0,1]
# np.random.rand(quantidade_de_numero_decimal_que_precisa)
np.random.rand(7)

##### Distribucao normal

In [ ]:
# numero aleatorio com distribuicao normal (medio=0, desvio_padrao = 1)
# intervalo [-1,1]
np.random.randn(6)

In [ ]:
# media de 6
np.random.normal(6)

In [ ]:
# media de 6, desvio_padrao = 5
np.random.normal(6, 5)

In [ ]:
# np.random.normal(meia, desv_padr, quantidade_de_numero)
np.random.normal(6,5,10)

### Opracoes e Calculos
__Operacoes:__
- min, max, media, soma, etc


In [ ]:
matriz

In [ ]:
matriz.max()

In [ ]:
matriz.mean()

In [ ]:
matriz.max( ) - matriz.min()

__Calculos:__
- Raiz quadrada
- cos, sen, tan
- log, exp, polinomial, etc

In [ ]:
matriz = np.arange(30, 60)
matriz

In [ ]:
matriz - 1000

In [ ]:
matriz + 1000

In [ ]:
matriz / 59

###### operaoes avancadas

In [ ]:
np.sqrt(matriz)

In [ ]:
np.log(matriz)

##### NumPy e mais eficiene que que Loop de Python, vejamos

In [ ]:
from datetime import datetime as dt

In [ ]:
dt.now().time()

In [ ]:
# 1 ate cem mil
matriz  = np.arange(1,100000)

In [ ]:
t_inicial = dt.now()

total = 0
for i in matriz:
    total += i

print(total)
dt.now() - t_inicial

In [ ]:
t_inicial = dt.now()

print(sum([i for i in matriz]))

dt.now() - t_inicial

In [ ]:
t_inicial = dt.now()

print(np.sum(matriz))

dt.now() - t_inicial

In [ ]:
(1- 34906/46873) * 100

In [ ]:
(1- 999/46873) * 100