# NumPy

- [NumPy GitHub](https://github.com/numpy/numpy)
- [NumPy website](https://numpy.org/)

NumPy e uma biblioteca fundamental para computação científica com Python.


Foi desenvolvida para linguagem de programação Python, permite a realização de operações matriciais, suportando grande e matrizes multidimensionais, além de possuir grande coleção de funções matemáticas de alto nível operando com matrizes.


E uma das bibliotecas de raiz existente na distribuicao de Anaconda (distribuicao de Python).

### Importacao de NumPy

In [1]:
import numpy as np

##### Lista de dados

In [2]:
for num in range(1, 15):
    print(num)

1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [3]:
lista = list(range(1,15))

In [4]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [6]:
# minha lista: m_lista
m_lista = [num for num in range(1, 15) if num % 5 == 3]
m_lista

[3, 8, 13]

In [7]:
# outra_lista 
o_lista = [[1,2,3], [4,5,6], [7,8,9], ['a', 'b', 'c', ['mm', 'bb']]]
o_lista

[[1, 2, 3], [4, 5, 6], [7, 8, 9], ['a', 'b', 'c', ['mm', 'bb']]]

In [13]:
o_lista[3][3][1]

'bb'

#### Matrizes

In [14]:
# matriz
np.array(o_lista)

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9]),
       list(['a', 'b', 'c', ['mm', 'bb']])], dtype=object)

In [15]:
# vector
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
vec = np.arange(5, 20)
vec

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
vec[[4,5,9]]

array([ 9, 10, 14])

In [18]:
vec.shape

(15,)

In [19]:
# np.linspace(inicio, fim, quantia_divisao)
np.linspace(1, 500, 13)

array([  1.        ,  42.58333333,  84.16666667, 125.75      ,
       167.33333333, 208.91666667, 250.5       , 292.08333333,
       333.66666667, 375.25      , 416.83333333, 458.41666667,
       500.        ])

#### seccionar

In [20]:
matriz = np.arange(1, 50)
matriz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [21]:
# do inicio ate 20
parte_matriz = matriz[:20]
parte_matriz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
# de 20 ate 30
matriz[20:30]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
matriz[20:]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [24]:
matriz[-1]

49

In [ ]:
matriz[-49]

In [25]:
# os ultimos 5
matriz[-7:]

array([43, 44, 45, 46, 47, 48, 49])

##### substituir

In [26]:
parte_matriz[:] = 5500

In [27]:
matriz

array([5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500,
       5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49])

In [28]:
matriz.reshape((7,7))

array([[5500, 5500, 5500, 5500, 5500, 5500, 5500],
       [5500, 5500, 5500, 5500, 5500, 5500, 5500],
       [5500, 5500, 5500, 5500, 5500, 5500,   21],
       [  22,   23,   24,   25,   26,   27,   28],
       [  29,   30,   31,   32,   33,   34,   35],
       [  36,   37,   38,   39,   40,   41,   42],
       [  43,   44,   45,   46,   47,   48,   49]])

In [29]:
matriz > 40

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

## Aleatorio (random)
#### Semente (seed) para guarantir a repeticao nas mesma condicao

In [39]:
np.random.seed(2020)
np.random.rand(4)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571])

In [47]:
np.random.rand(4)

array([0.37339376, 0.37969293, 0.85831659, 0.64606105])

__Inteiro__

In [52]:
# numeros inteiros aleatorios
np.random.randint(1000)

294

In [54]:
# lista de numero  aleaotrio  inteiro
np.random.randint(1, 45, 5)

array([16, 31, 21, 23, 27])

In [55]:
np.random.randint(0,10, 2)

array([6, 8])

__Decimal__

In [56]:
# numero aleatorio no intervalo [0,1]
# np.random.rand(quantidade_de_numero_decimal_que_precisa)
np.random.rand(7)

array([0.790756  , 0.62642031, 0.84408418, 0.90133065, 0.80555116,
       0.53083765, 0.93513166])

##### Distribucao normal

In [57]:
# numero aleatorio com distribuicao normal (medio=0, desvio_padrao = 1)
# intervalo [-1,1]
np.random.randn(6)

array([-0.59212641,  1.88113822, -0.8227176 ,  0.47159117,  0.35489576,
        0.85495514])

In [58]:
# media de 6
np.random.normal(6)

5.621976461142936

In [59]:
# media de 6, desvio_padrao = 5
np.random.normal(6, 5)

8.719038683080518

In [60]:
# np.random.normal(meia, desv_padr, quantidade_de_numero)
np.random.normal(6,5,100)

array([ 1.48243817e+01,  3.44351310e+00,  3.30970467e+00,  3.00861761e+00,
        5.40801023e+00,  3.75146061e+00,  1.01877063e+01,  1.02291459e+01,
        1.17180330e+01,  1.10766374e+01,  2.88388196e+00,  1.30909261e+01,
       -4.18484960e+00,  3.50205145e+00,  3.36071286e+00,  2.34366543e+00,
        8.62541531e+00,  1.15004171e+01,  1.05151513e+01,  1.62648005e+00,
       -5.72146774e+00,  9.24408650e+00,  1.05921714e+01,  2.33801162e+01,
        4.49449462e-01,  6.67341892e+00,  2.93399239e+00,  5.44670405e+00,
        9.18385799e+00,  2.45339507e+00,  4.29825091e+00,  5.50252014e+00,
        1.44135607e+01,  7.17535755e+00,  7.95827491e+00,  1.09159277e+01,
        1.04892721e+01,  1.23029893e+01,  1.19926044e+01,  9.81838971e+00,
        1.12154319e+01,  9.56424262e+00,  9.23397609e+00,  1.01516074e+01,
        1.28203579e+01,  4.37185579e+00,  4.58693401e+00,  1.22624825e+01,
        2.00428031e+00, -2.35147167e-01,  3.28067549e+00,  2.10274598e+00,
        2.63083539e+00,  

### Opracoes e Calculos
__Operacoes:__
- min, max, media, soma, etc


In [61]:
matriz

array([5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500,
       5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500, 5500,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49])

In [62]:
matriz.max()

5500

In [63]:
matriz.mean()

2265.612244897959

In [64]:
matriz.max( ) - matriz.min()

5479

__Calculos:__
- Raiz quadrada
- cos, sen, tan
- log, exp, polinomial, etc

In [65]:
matriz = np.arange(30, 60)
matriz

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [66]:
matriz - 1000

array([-970, -969, -968, -967, -966, -965, -964, -963, -962, -961, -960,
       -959, -958, -957, -956, -955, -954, -953, -952, -951, -950, -949,
       -948, -947, -946, -945, -944, -943, -942, -941])

In [67]:
matriz + 1000

array([1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040,
       1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051,
       1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059])

In [68]:
matriz / 59

array([0.50847458, 0.52542373, 0.54237288, 0.55932203, 0.57627119,
       0.59322034, 0.61016949, 0.62711864, 0.6440678 , 0.66101695,
       0.6779661 , 0.69491525, 0.71186441, 0.72881356, 0.74576271,
       0.76271186, 0.77966102, 0.79661017, 0.81355932, 0.83050847,
       0.84745763, 0.86440678, 0.88135593, 0.89830508, 0.91525424,
       0.93220339, 0.94915254, 0.96610169, 0.98305085, 1.        ])

###### operaoes avancadas

In [71]:
matriz**(1/2)

array([5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575])

In [69]:
np.sqrt(matriz)

array([5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575])

In [70]:
np.log(matriz)

array([3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ,
       3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744])

##### Series Temporais


-  Referencia para todos os codigos formais associados as Data e Series Temporais

- [Codigos de dados temporais](https://www.w3schools.com/python/python_datetime.asp)

In [75]:
# S - Segundos (00-59)
# M - Minutos (00-60)
# d - Dias (01-31)
# w - Semanas (1-56)
# m - Mes (01-12);        B - mes (Janeiro-Dezembro)
# Y - Ano (2020);         y - ano (20)

# Data independencia de STP
np.arange('1975-07-12', '2020-07-12', dtype = 'datetime64[h]').shape

(394488,)

##### NumPy e mais eficiene que que Loop de Python, vejamos

In [76]:
from datetime import datetime as dt

In [77]:
dt.now().time()

datetime.time(7, 3, 51, 170729)

In [78]:
# 1 ate cem mil
matriz  = np.arange(1,100000)

In [79]:
t_inicial = dt.now()

total = 0
for i in matriz:
    total += i

print(total)
dt.now() - t_inicial

704982704


C:\Users\lmanu\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in long_scalars
  """


datetime.timedelta(microseconds=81781)

In [80]:
t_inicial = dt.now()

print(sum([i for i in matriz]))

dt.now() - t_inicial

704982704


C:\Users\lmanu\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in long_scalars
  This is separate from the ipykernel package so we can avoid doing imports until


datetime.timedelta(microseconds=56859)

In [83]:
t_inicial = dt.now()

print(np.sum(matriz))

dt.now() - t_inicial

704982704


datetime.timedelta(microseconds=998)